### PR TITLE
option to add http headers when retrieving pdf document from url

### PR DESCRIPTION
**Pull request by mmcdon20**
This will allow users to add http headers:

`PDFDocument doc = await PDFDocument.fromURL('http://www.africau.edu/images/default/sample.pdf', headers: { 'header-name': 'header-value' });`

### CODE REVIEW

**Comment by allanwolski** [comment]
I need this too.

**Comment by mofada** [comment]
I need this too.

**Comment by christianmls** [comment]
Me too

**Comment by christianmls** [comment]
Me too

**Comment by ogata-k** [comment]
Me too

**Comment by darmawan01** [comment]
really need this future

**Pull request closed without merging**
